export const CLEAR_CORONAINDONESIALIST = 'CLEAR_CORONAINDONESIALIST';
export const LOAD_CORONAINDONESIALIST = 'LOAD_CORONAINDONESIALIST';

export const CLEAR_CORONAPROVINSILIST = 'CLEAR_CORONAPROVINSILIST';
export const LOAD_CORONAPROVINSILIST = 'LOAD_CORONAPROVINSILIST';